### PR TITLE
fix(2115): add metrics plugins

### PR DESCRIPTION
**Pull request by s-yoshika**
## Context
Screwdriver.cd has no application metrics, except build metrics, and cluster admins are hard to find what problems is happend on the application, for example, 500 error is happend or performances are degraded.

## Objective
To detect these problems, This PR adds the [promster](https://github.com/tdeekens/promster) plugins to collect the metrics about nodejs and http.
- `plugins/promster.js` to collect http and nodejs metrics
- `plugins/metrics.js` to expose the collected metrics

It can collect the metrics like following
image

Please refer the documents for more details
https://github.com/tdeekens/promster#-documentation

## References
https://github.com/screwdriver-cd/screwdriver/issues/2115
https://github.com/tdeekens/promster

## License
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by s-yoshika** [comment]
@jithine 
In my local environment, I have confirmed that it can collect the metrics with following `scrape_configs` settings in `prometheus.yml`. Especially, we have to set `metrics_path` to `/v4/metrics`. Should I add this to the guide?
```
scrape_configs:
  - job_name: 'screwdriver-cd'
    metrics_path: /v4/metrics
    static_configs:
      - targets:
          - localhost:9001
```

**Comment by tkyi** [comment]
Yes! would be awesome to have an entry for this in the guide

**Comment by s-yoshika** [comment]
@tkyi @jithine I added metrics page to the guide.
https://github.com/screwdriver-cd/guide/pull/399
And add prefix `sd_` as same as build metrics https://github.com/screwdriver-cd/screwdriver/pull/2155/commits/f5caa7f81b614d74577045916a3e30a9e34c2766.

**Comment by jithine** [comment]
can you rebase this ? looks like can't auto merge.

**Comment by s-yoshika** [comment]
@jithine Sorry, I rebased this.

**Pull request merged**
