### PR TITLE
feat(587): Skip builds when commit message includes [skip ci]

### PR DESCRIPTION
**Pull request by catto**
## Context

I'd like to implement feature reported at #587 

## Objective

Build will skip when the last commit message includes "[skip ci]" or "[ci skip]".
Changes needed for this feature has already been implemented at https://github.com/screwdriver-cd/scm-github/issues/64 and https://github.com/screwdriver-cd/scm-bitbucket/issues/40.
`/webhook` will reply 204 when the build is skipped.

## References

* Original issue: #587

### CODE REVIEW

**Comment by catto** [comment]
@d2lam done!

**Comment by catto** [comment]
ah.. one more time

**Comment by tkyi** [comment]
@catto Sorry 🙇‍♀️

**Comment by catto** [comment]
@tkyi no worries! build passed 🐈

**Pull request merged**
