### PR TITLE
improve in-a-box

### PR DESCRIPTION
**Pull request by wahapo**
modify some parts of this issue https://github.com/screwdriver-cd/screwdriver/issues/321

> Small:
>
> - [x] Do requirement checking (docker, docker-compose, openssl)
> - [x] Tell user what to put in 'Homepage URL' for GitHub OAuth
> - [x] Warn user about Webhooks/PRs not working
> - [x] Perform a pull before starting to get latest stable images

How does it look?

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by stjohnjohnson** [comment]
Looks great @wahapo!!  I love the icons you picked!

**Comment by wahapo** [comment]
Thanks all for review!
cla/licenses failed😢  I signed yahoocla just now. Do I have to do something else?

**Comment by wahapo** [comment]
Oh! cla/licenses was a success❤️

**Pull request merged**
