### PR TITLE
docs(621): Link CONTRIBUTING.md to actual Contributing docs

### PR DESCRIPTION
**Pull request by r3rastogi**
The Contributing section of the Screwdriver.cd docs is more
comprehensive and better formatted than the information within the
CONTRIBUTING.md on Github. All the information that was on the Github
page is already included in the docs, so this PR also removes that
redundancy.

Related to: https://github.com/screwdriver-cd/screwdriver/issues/621

### CODE REVIEW

**Comment by tkyi** [comment]
I like the idea but the contributing doc is kind of out of date in the guide. Are we also planning to update all the contributing docs in every repo? We should probably also update the [generator-screwdriver](https://github.com/screwdriver-cd/generator-screwdriver).

**Comment by r3rastogi** [comment]
The guide contributing doc is more up-to-date than this one, and I'm currently working on adding a lot more information to it.

I don't have a strong opinion either way of updating the contributing docs in all repos, but this one makes sense because it's the central repo for Screwdriver.cd and the probably the first place people  will look to when trying to make changes.

> We should probably also update the generator-screwdriver.

Do you mean just the CONTRIBUTING.md there, or something else?

**Comment by tkyi** [comment]
@r3rastogi Yes, we should update all the CONTRIBUTING.md docs in there as well, since people will use those templates to make new repos in the future.

**Comment by r3rastogi** [comment]
@tkyi mkay will update there as well

**Pull request merged**
