### PR TITLE
Run Cucumber tests in wercker

### PR DESCRIPTION
**Pull request by tkyi**
- Added INSTANCE environment variable in Wercker
- Add run Cucumber test step in Wercker yaml

### CODE REVIEW

**Comment by FenrirUnbound** [comment]
👍 

Looks fine to me

**Comment by petey** [comment]
👍

**Comment by FenrirUnbound** [comment]
> Won't this cause build failures until all the step-definitions are written?

It skips the undefined ones. They were ran during this PR's wercker build, so you can verify it there as well

**Comment by jer** [comment]
👍

**Comment by Filbird** [comment]
Looks gr8 👍

**Pull request merged**
