### PR TITLE
Add crumb issuer

### PR DESCRIPTION
**Pull request by catto**
I added a crumb issuer for write accesses. #144 
* Implemented as a plugin for v3 route (`/v3/crumb`)
* All accesses to POST, PUT and DELETE endpoints are verified with the crumb.
* Crumb needs to be passed by `X-CSRF-Token` header.

### CODE REVIEW

**Comment by stjohnjohnson** [comment]
Awesome job, @catto.

We should turn off crumb protection on the webhooks endpoints as GitHub and the Launcher do not support crumb.

How does this work for multiple replicas?  If we run two of them on kubernetes, what do they use to validate the crumb the other one issued?

**Comment by catto** [comment]
Ah, I forgot webhooks completely. I have turned off crumb protection on the webhooks endpoints.

Hapi crumb plugin reads the cookie named `crumb` and compares it with the passed crumb.
https://github.com/hapijs/crumb/blob/master/lib/index.js#L167
So it works for multiple instances because of this behavior. I verified it by issuing a new crumb, restarting the server and posting it to a test endpoint.

**Comment by stjohnjohnson** [comment]
👍  
giphy 5

**Comment by nkatzman** [comment]
Are crumb's required when a jwt is being sent?

**Comment by stjohnjohnson** [comment]
Good catch, @nkatzman.  I guess crumbs should only be required when using cookies, JWTs should be enough for CSRF.

**Comment by catto** [comment]
You have a point. I have added `skip` function to check a request is under `webhook` or jwt is used. Also, added tests for it.

**Comment by nkatzman** [comment]
Cool 👍

**Comment by stjohnjohnson** [comment]
👍

**Comment by stjohnjohnson** [comment]
Thanks @catto!  You rock!

**Comment by catto** [comment]
:cat2:

**Pull request merged**
