### PR TITLE
[small] add event to emit data

### PR DESCRIPTION
**Pull request by yokawara**
## Context
We want to enrich infomations of notifications.

## Objective
Pass event, build, pipeline data to notification plugins.

relates:
https://github.com/screwdriver-cd/notifications-email/pull/16
https://github.com/screwdriver-cd/notifications-slack/pull/13

### CODE REVIEW

**Comment by tk3fftk** [comment]
This fix may cause validation error on notifications-email.

**Comment by yokawara** [comment]
> This fix may cause validation error on notifications-email.

I will fix that, thank you!

**Comment by yokawara** [comment]
@jithin1987 Could you review this PR?

**Comment by tkyi** [comment]
This looks really cool! What are you planning to do with this extra data? We want to make our notifications pretty, too!

**Comment by yokawara** [comment]
@tkyi For now, we are planning to add informations for example,
 * Who and how triggered a event (build)
* Link of the github commit (pr) which triggered a event (build)

Let us know when you got some nicer idea 😄

**Comment by tkyi** [comment]
@yokawara That sounds really cool. We are very interested in seeing the end result!
We haven't been looking into notifications much, but some people have been asking for customizable Slack notifications: https://github.com/screwdriver-cd/screwdriver/issues/1177

**Pull request merged**
