### PR TITLE
Add license declaration

### PR DESCRIPTION
**Pull request by BenLloydPearson**
## Context

This makes it clear that contributors are giving code to the project under the BSD license.

## Objective

This ensures that contributions are protected under the terms of the BSD license and prevents the ability to revoke access to code that is contributed to this project.

### CODE REVIEW

**Comment by tkyi** [comment]
@BenLloydPearson Does this statement mean contributors no longer need to sign a CLA?

Also, can we set this as the template for all other Screwdriver repos? I like the Context, Objective, and Related links headers/formatting much better

**Comment by BenLloydPearson** [comment]
@tkyi yes, this means contributors no longer need to sign the CLA when opening a PR. However, people will still need to sign before we grant them write access to this repo.

I will add the headers to the default PR template too.

**Comment by tkyi** [comment]
@BenLloydPearson Ah, will the CLA check be removed from all repos?

**Comment by BenLloydPearson** [comment]
Yes, I will remove it.

**Pull request merged**
