### PR TITLE
Accessibility review for ScrewDriver

### PR DESCRIPTION
**Pull request by rishu2403**
Reviewed and compiled a report for Screwdriver project according to WCAG 2.0 .

## License
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by jithine — CHANGES_REQUESTED** [review]
Can you upload in markdown / pdf format rather than in binary

**Comment by jithine** [comment]
Doc looks good, but I don't this this is the correct place to add this file. Can you attach the file to the original issue ? https://github.com/screwdriver-cd/screwdriver/issues/2384 We can open another issue for fixing accessibility issues and use this report as reference.

**Comment by rishu2403** [comment]
> 
> 
> Doc looks good, but I don't think this is the correct place to add this file. Can you attach the file to the original issue ? #2384 We can open another issue for fixing accessibility issues and use this report as reference.

Thank you , PDF attached in the original issue.

**Comment by jithine** [comment]
Closing this issue. Created https://github.com/screwdriver-cd/screwdriver/issues/2402 to track work.

**Pull request closed without merging**
